language: rust
cache: cargo
rust:
    - nightly
before_script:
    - rustup component add rustfmt
script:
    - cargo build --all
    - cargo test --all
    - cargo fmt -- --check
after_success:
  - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh success $WEBHOOK_URL
after_failure:
  - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh failure $WEBHOOK_URL