cargo-features = ["default-run"]
[package]
name = "carbonbond"
version = "0.1.0"
authors = ["金剛 <yc1043@gmail.com>", "石墨 <why8ther@gmail.com>"]
edition = "2018"
default-run = "server"

[dependencies]
diesel = { version = "~1", features = ["postgres"] }
actix-web = "~1"
log = "~0"
env_logger = "~0"
dotenv = "~0"
rand = "~0"
rust-argon2 = "~0"
juniper = "~0"
serde_json = "~1"
serde = { version = "~1", features = ["derive"] }
actix-files = "~0"
actix-rt = "~0"
actix-session = "~0"
regex = "~1"
failure = "~0"
clap = {version = "~2", features = ["yaml"]}
toml = "~0"

[[bin]]
name = "server"
path = "src/main.rs"

[[bin]]
name = "db-tool"
path = "src/db_tool.rs"

[lib]
doctest = false