# 若本地環境與此設定檔有出入，請勿直接修改本檔案，應另創建一份 carbonbond.local.toml 設定檔

[server]
address = "localhost"
port = 8080
# mailgun_key_file 為一個檔案位置
mailgun_key_file = "config/secret/MAILGUN_KEY.example"

[database]
# url 的格式為 "postgres://[用戶名]:[密碼]@[資料庫位址]:[埠口]/[資料庫名]"
url = "postgres://postgres@localhost:5432/carbonbond"
